name: flutter_app
description: "A production-level Flutter project with GetX state management."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
 
  get: ^4.6.6
  
  http: ^1.2.0
  
  json_annotation: ^4.9.0

#-------------[Development Dependencies]-------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true


#-----------------[assets]-------------
assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/
  - assets/animations/
  - assets/videos/
  - assets/sounds/
  - assets/documents/
  - assets/spreadsheets/
  - assets/presentations/
  - assets/pdfs/

#-----------------[fonts]-------------
fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400 
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 800
      - asset: assets/fonts/Nunito-Italic.ttf
        weight: 400
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
   