name: ecommerce_app
description: "Easy Commerce is a production-level Flutter application built with GetX state management, clean architecture, and a modern UI."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

#-------------------------[dependencies]--------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
 
  get: ^4.7.2
  
  http: ^1.2.0
  
  json_annotation: ^4.9.0


  #------------------utilities--------------------------
  #spalash screen
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  smooth_page_indicator: ^1.2.1
  
#-------------[Development Dependencies]-------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true

  #-----------------[assets]-------------
  assets:
    - assets/logo/
    - assets/animations/

  #-----------------[fonts]-------------
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
   